Fix integer type narrowing conversion error in AGX Archive Reader
Got the following build error with previous code:

Error C2397 conversion from 'int' to 'size_t' requires a narrowing conversion AGXUnrealDev C:\Algoryx\agxunreal\AGXUnrealDev\Plugins\AGXUnreal\Source\AGXUnrealBarrier\Private\AGXArchiveReader.cpp 121